name: fox

services:
  backend:
    container_name: fox-api
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file:
      - ./.env
    user: python
    command: uv run uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
    ports:
      - 80:80
    volumes:
      # bind mount folder with data
      - ./api/data:/opt/python/data
    develop:
      # Create a `watch` configuration to update the app
      watch:
        # Sync the working directory with the directory in the container
        - action: sync
          path: ./api
          target: /opt/python
          # Exclude the project virtual environment and data folder
          ignore:
            - .venv/
            - data/
        # Rebuild the image if dependencies change by checking `pyproject.toml`
        - action: rebuild
          path: ./pyproject.toml
        - action: rebuild
          path: uv.lock
